version: '3'

services:
  # RTMP server for receiving RTMP streams
  rtmp-server:
    build:
      context: .
      dockerfile: Dockerfile.rtmp
    container_name: rtmp-server
    ports:
      - "1935:1935"  # RTMP port
    restart: unless-stopped
    networks:
      - stream-network

  # RTSP server for serving RTSP streams
  rtsp-server:
    build:
      context: .
      dockerfile: Dockerfile.rtsp
    container_name: rtsp-server
    ports:
      - "8554:8554"  # RTSP port
    restart: unless-stopped
    networks:
      - stream-network

  # RTMP to RTSP converter service
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtmp-rtsp-converter
    ports:
      - "3000:3000"  # Web interface
    environment:
      - RTMP_PORT=1935
      - RTSP_PORT=8554
      - WEB_PORT=3000
      - LOG_LEVEL=info
      - RTSP_BASE_URL=rtsp://rtsp-server:8554
      - RTMP_SERVER=rtmp://rtmp-server:1935
    volumes:
      - converter-data:/app/temp
    depends_on:
      - rtmp-server
      - rtsp-server
    restart: unless-stopped
    networks:
      - stream-network

  # Test stream generator (optional, for demo purposes)
  test-stream:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-stream
    depends_on:
      - rtmp-server
    restart: unless-stopped
    networks:
      - stream-network

networks:
  stream-network:
    driver: bridge

volumes:
  converter-data:
